### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by netopir** [otsaloma/nfoview#18]
Hello
Can you make a installer for the v1,28 version 
THX

**Comment by otsaloma** [comment]
I stopped making those due to bad tooling and bad results. I might revisit that sometime in the future.

**Comment by otsaloma** [comment]
I looked into this a bit and it doesn't look sensible to return to Windows-packaging. I updated the README to reflect that.

https://github.com/otsaloma/nfoview/commit/417362ea4d3f42464ea7c0608b814377e46f30df
