### ISSUE TITLE
appstream 'mimetypes' tag is deprecated

### ISSUE THREAD

**Issue by jcfp** [otsaloma/nfoview#21]
The toplevel `mimetypes` tag (used in _io.otsaloma.nfoview.appdata.xml_) is deprecated in favour of `mediatype` tags in a `provides` block to indicate that your software provides a media handler for the given types. 

See [docs](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-mimetypes) at freedesktop.org.

**Comment by otsaloma** [comment]
Thanks for noticing, fixing now.
