### ISSUE TITLE
GNOME 42 runtime is no longer supported

### ISSUE THREAD

**Issue by jrabensc** [otsaloma/nfoview#23]
Hi,

I'm getting this message when installing nfoview:

> The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.otsaloma.nfoview

**Comment by otsaloma** [comment]
Flathub: https://github.com/flathub/io.otsaloma.nfoview/pull/5

**Comment by otsaloma** [comment]
Updated now
