### ISSUE TITLE
nfoview showing raw tags

### ISSUE THREAD

**Issue by R8s6** [otsaloma/nfoview#26]
Hi,

I installed nfoview on Arch and it's still showing the raw tags (just like any other regular text editors).

Is it supposed to display like the following, or perhaps a packaging issue?  Thanks!

![](https://i.imgur.com/7yA1OAW.png)

**Comment by otsaloma** [comment]
That's a different file format, some kind of XML.

**Comment by R8s6** [comment]
i see, i found another .nfo file and it displays correctly.

case closed, thanks.
