### ISSUE TITLE
v2.0.0/v2.0.1 - Flatpak problem

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [otsaloma/nfoview#27]
Hi @otsaloma!

I would like to report, that for me on Ubuntu, seems the latest version(s) is not working properly, as the following describes it:

```bash
$flatpak run io.otsaloma.nfoview    
Traceback (most recent call last):
  File "/app/bin/nfoview", line 6, in <module>
    import nfoview
ModuleNotFoundError: No module named 'nfoview'
```

Lot of thanks, if you could turn me into the right direction...

**Comment by otsaloma** [comment]
Thanks for reporting. It seems `make build` is missing the prefix. I'll fix it.

**Comment by otsaloma** [comment]
Pushing to Flathub as well. Once the PR is merged it should update at some delay.

https://github.com/flathub/io.otsaloma.nfoview/pull/9

**Comment by Tamas-Toth-ebola** [comment]
Can confirm, that works like a charm :wink: 

Thanks for it!
