### ISSUE TITLE
No selected text background

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/nfoview#5]
With GTK+ 3.18 from pygi-aio.

**Comment by Achaean** [comment]
**Hi!** :-)

I have the same behavior on Linux too (Debian Jessie x64 KDE).
I think, it's now Windows specific.
G.

**Comment by otsaloma** [comment]
OK. Jessie seems to have GTK+ 3.14. So, it's probably related to the GTK+ version, maybe anything less than 3.20. The GTK+ 3.x styling has been such a fast-moving target that it's not surprising that there are issues. I'm not likely to actively try to fix these non-critical issues in old versions of GTK+, but if someone has a fix to provide that doesn't break anything in later versions, I'll gladly accept it.

**Comment by otsaloma** [comment]
Closing as per the previous comment.
